# Generated by Django 4.0.1 on 2022-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='homeImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
