# Generated by Django 4.0.1 on 2022-01-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_homeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='homeImage',
            new_name='categoryImage',
        ),
    ]
